#Requires -Version 5.1
<#
.SYNOPSIS
  Bumps installer BUILD_NUMBER and writes VERSION.txt + version.inc.iss for packaging.
#>
[CmdletBinding()]
param(
    [switch] $NoBump
)

$ErrorActionPreference = "Stop"
$InstallerDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $InstallerDir
$BuildFile = Join-Path $InstallerDir "BUILD_NUMBER"
$VersionTxt = Join-Path $ProjectRoot "VERSION.txt"
$VersionInc = Join-Path $InstallerDir "windows\version.inc.iss"

if (-not (Test-Path $BuildFile)) {
    Set-Content -LiteralPath $BuildFile -Value "1" -Encoding ascii
}

$raw = (Get-Content -LiteralPath $BuildFile -Raw).Trim()
if ($raw -notmatch '^\d+$') {
    throw "BUILD_NUMBER must be a positive integer (got: $raw)"
}
$build = [int]$raw
if (-not $NoBump) {
    $build++
    Set-Content -LiteralPath $BuildFile -Value "$build" -Encoding ascii
}

$version = "1.0.$build"
$builtAt = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
$gitSha = ""
try {
    Push-Location $ProjectRoot
    $gitSha = (& git rev-parse --short HEAD 2>$null)
    if (-not $gitSha) { $gitSha = "" }
}
catch {
    $gitSha = ""
}
finally {
    Pop-Location
}

$versionBody = @(
    "Product: MultiLogicTradePg"
    "Version: $version"
    "Build: $build"
    "Built: $builtAt"
    $(if ($gitSha) { "Git: $gitSha" } else { $null })
) | Where-Object { $_ }
Set-Content -LiteralPath $VersionTxt -Value ($versionBody -join [Environment]::NewLine) -Encoding utf8

$inc = @(
    "; Auto-generated by installer/Sync-InstallerVersion.ps1 - do not edit by hand."
    "#define MyAppVersion `"$version`""
    "#define MyAppBuild `"$build`""
)
Set-Content -LiteralPath $VersionInc -Value ($inc -join [Environment]::NewLine) -Encoding ascii

Write-Host "Installer version: $version (build $build)" -ForegroundColor Cyan
Write-Host "  $VersionTxt"
Write-Host "  $VersionInc"

return [pscustomobject]@{
    Build   = $build
    Version = $version
    Path    = $VersionTxt
}
