; MultiLogicTradePg Windows installer.
; Build with installer/windows/build-installer.ps1 or Inno Setup Compiler (ISCC.exe).
; version.inc.iss is generated by installer/Sync-InstallerVersion.ps1 (build number).
#include "version.inc.iss"
#define MyAppName "MultiLogicTradePg"
#define MyAppPublisher "RobinZGit"
#ifndef MyAppVersion
#define MyAppVersion "1.0.0"
#endif
#ifndef MyAppBuild
#define MyAppBuild "0"
#endif
#define MyAppExeName "Start_MultiLogic_Trade.cmd"
#define MyAppBatName "MultiLogic_Trade_Progress_Start.bat"
#define MyAppServerBatName "MultiLogic_Trade_Server_Start.bat"
#define MyAppServerCmdName "Start_MultiLogic_Trade_Server.cmd"
#define MyAppId "{D8F3A59E-59FD-4A83-BC26-FD0A671E01A9}"
#define SourceRoot "..\.."

[Setup]
AppId={{D8F3A59E-59FD-4A83-BC26-FD0A671E01A9}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion} (build {#MyAppBuild})
AppPublisher={#MyAppPublisher}
VersionInfoVersion={#MyAppVersion}.0
VersionInfoProductVersion={#MyAppVersion}
VersionInfoProductName={#MyAppName}
UninstallDisplayName={#MyAppName} {#MyAppVersion} (build {#MyAppBuild})
DefaultDirName={autopf}\MultiLogicTradePg
DefaultGroupName=MultiLogic Trade
DisableProgramGroupPage=yes
OutputDir=dist
OutputBaseFilename=MultiLogicTradePgSetup
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
PrivilegesRequired=admin
SetupLogging=yes
UninstallDisplayIcon={sys}\cmd.exe

[Languages]
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

; Bottom strip on every wizard page (always visible).
[Messages]
BeveledLabel=Version {#MyAppVersion}  |  Build {#MyAppBuild}
russian.BeveledLabel=Версия {#MyAppVersion}  |  Сборка {#MyAppBuild}
english.BeveledLabel=Version {#MyAppVersion}  |  Build {#MyAppBuild}

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: checkedonce
; Opt-in: Mozilla CA + Russian Trusted CA (Госуслуги/НУЦ) for pgsql-http / T-Bank. Default OFF.
Name: "updatesslcerts"; Description: "{cm:UpdateSslCertsTask}"; GroupDescription: "{cm:SslCertsGroup}"; Flags: unchecked

[CustomMessages]
russian.UpdateSslCertsTask=Установить/обновить SSL CA для Postgres (Mozilla + сертификаты Госуслуг/НУЦ Минцифры для T-Bank API)
english.UpdateSslCertsTask=Install/update Postgres SSL CAs (Mozilla + Gosuslugi/MinTsifry Russian Trusted CA for T-Bank API)
russian.SslCertsGroup=Сертификаты T-Bank / Госуслуги (по умолчанию выкл.):
english.SslCertsGroup=T-Bank / Gosuslugi certificates (off by default):

[Files]
Source: "{#SourceRoot}\00_create_database.sql"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceRoot}\01_multilogictrade_tables_and_data.sql"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceRoot}\02_multilogictrade_functions_and_procedures.sql"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceRoot}\03_multilogictrade_examples.sql"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceRoot}\README.md"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceRoot}\VERSION.txt"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceRoot}\installer\windows\INSTALL_PROTOCOL.placeholder.txt"; DestDir: "{app}"; DestName: "INSTALL_PROTOCOL.txt"; Flags: ignoreversion
Source: "{#SourceRoot}\docs\*"; DestDir: "{app}\docs"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#SourceRoot}\scripts\*"; DestDir: "{app}\scripts"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "_tmp_http_ext\*"
Source: "{#SourceRoot}\sql\*"; DestDir: "{app}\sql"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#SourceRoot}\api\*"; DestDir: "{app}\api"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "node_modules\*,.env"
Source: "{#SourceRoot}\web\*"; DestDir: "{app}\web"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "node_modules\*,.angular\*,dist\*"
Source: "{#SourceRoot}\installer\windows\*"; DestDir: "{app}\installer\windows"; Flags: ignoreversion recursesubdirs createallsubdirs; Excludes: "dist\*"

[Icons]
; Launch via cmd.exe /k so the console stays open (Explorer shortcuts to .bat/.cmd often flash and close).
Name: "{autoprograms}\MultiLogic Trade\MultiLogic Trade"; Filename: "{cmd}"; Parameters: "/k cd /d ""{app}\web"" && call ""{app}\web\{#MyAppBatName}"""; WorkingDir: "{app}\web"; Comment: "Запустить MultiLogic Trade (API + Angular UI)"
Name: "{autoprograms}\MultiLogic Trade\MultiLogic Trade Server (API only)"; Filename: "{cmd}"; Parameters: "/k cd /d ""{app}\web"" && call ""{app}\web\{#MyAppServerBatName}"""; WorkingDir: "{app}\web"; Comment: "Только API — без Angular (явно без UI)"
Name: "{autoprograms}\MultiLogic Trade\Install protocol"; Filename: "{win}\notepad.exe"; Parameters: """{app}\INSTALL_PROTOCOL.txt"""; WorkingDir: "{app}"; Comment: "Открыть протокол установки MultiLogicTradePg"
Name: "{autodesktop}\MultiLogic Trade"; Filename: "{cmd}"; Parameters: "/k cd /d ""{app}\web"" && call ""{app}\web\{#MyAppBatName}"""; WorkingDir: "{app}\web"; Comment: "Запустить MultiLogic Trade (API + Angular UI)"; Tasks: desktopicon

[Run]
; DbMode / UpdateSslCerts written in PreparePostInstall (read by run_postinstall.cmd).
Filename: "{cmd}"; Parameters: "/C """"{app}\installer\windows\scripts\run_postinstall.cmd"" ""{app}"" ""111"""""; StatusMsg: "Настройка приложения... См. INSTALL_PROTOCOL.txt"; Flags: waituntilterminated runhidden; BeforeInstall: PreparePostInstall; AfterInstall: FinishPostInstall
; Always open Angular UI after install unless the user unchecks this box.
Filename: "{cmd}"; Parameters: "/k cd /d ""{app}\web"" && call ""{app}\web\{#MyAppBatName}"""; WorkingDir: "{app}\web"; Description: "Open MultiLogic Trade UI (API + Angular)"; Flags: postinstall nowait skipifsilent runasoriginaluser
; Opt-in: API only, no Angular (explicit — leave unchecked by default).
Filename: "{cmd}"; Parameters: "/k cd /d ""{app}\web"" && call ""{app}\web\{#MyAppServerBatName}"""; WorkingDir: "{app}\web"; Description: "Start API only (no Angular UI)"; Flags: postinstall nowait skipifsilent unchecked runasoriginaluser
Filename: "{win}\notepad.exe"; Parameters: """{app}\INSTALL_PROTOCOL.txt"""; WorkingDir: "{app}"; Description: "Open installation protocol"; Flags: postinstall skipifsilent unchecked runasoriginaluser; Check: InstallProtocolExists

[Code]
var
  GDbMode: String;
  GInstalled: Boolean;
  GUninstallString: String;
  GUpgradePage: TWizardPage;
  GWipeDataCheck: TNewCheckBox;

function GetDbMode(Param: String): String;
begin
  if GDbMode = '' then
    Result := 'create'
  else
    Result := GDbMode;
end;

function StripQuotes(Value: String): String;
begin
  Result := Value;
  if (Length(Result) >= 2) and (Copy(Result, 1, 1) = '"') and (Copy(Result, Length(Result), 1) = '"') then
    Result := Copy(Result, 2, Length(Result) - 2);
end;

procedure InitializeWizard();
var
  TextLabel: TNewStaticText;
begin
  { Bottom strip on every wizard page. }
  if ActiveLanguage = 'russian' then
    WizardForm.BeveledLabel.Caption := 'Версия {#MyAppVersion}  |  Сборка {#MyAppBuild}'
  else
    WizardForm.BeveledLabel.Caption := 'Version {#MyAppVersion}  |  Build {#MyAppBuild}';

  { Welcome page: version and build first so they are obvious. }
  if ActiveLanguage = 'russian' then
  begin
    WizardForm.WelcomeLabel1.Caption := 'Установка MultiLogicTradePg';
    WizardForm.WelcomeLabel2.Caption :=
      'Версия: {#MyAppVersion}'#13#10 +
      'Сборка: {#MyAppBuild}'#13#10#13#10 +
      'Мастер установит MultiLogicTradePg на ваш компьютер.'#13#10#13#10 +
      'Нажмите «Далее» для продолжения.';
  end
  else
  begin
    WizardForm.WelcomeLabel1.Caption := 'MultiLogicTradePg Setup';
    WizardForm.WelcomeLabel2.Caption :=
      'Version: {#MyAppVersion}'#13#10 +
      'Build: {#MyAppBuild}'#13#10#13#10 +
      'This will install MultiLogicTradePg on your computer.'#13#10#13#10 +
      'Click Next to continue.';
  end;

  { Page 2 (only when an older copy is already installed): by default the
    database is kept (same as the old "No"), wiping happens only if the user
    ticks the checkbox (same as the old "Yes"). }
  if ActiveLanguage = 'russian' then
    GUpgradePage := CreateCustomPage(wpWelcome,
      'Обновление MultiLogicTradePg',
      'MultiLogicTradePg уже установлен — данные будут сохранены')
  else
    GUpgradePage := CreateCustomPage(wpWelcome,
      'Update MultiLogicTradePg',
      'MultiLogicTradePg is already installed - your data will be kept');

  TextLabel := TNewStaticText.Create(GUpgradePage);
  TextLabel.Parent := GUpgradePage.Surface;
  TextLabel.Left := 0;
  TextLabel.Top := 0;
  TextLabel.Width := GUpgradePage.SurfaceWidth;
  TextLabel.Height := 110;
  TextLabel.WordWrap := True;
  if ActiveLanguage = 'russian' then
    TextLabel.Caption :=
      'Новый пакет: версия {#MyAppVersion}, сборка {#MyAppBuild}.'#13#10#13#10 +
      'По умолчанию установка пройдёт поверх старой версии: существующие'#13#10 +
      'таблицы и данные (цены, сделки, логики, параметры индикаторов)'#13#10 +
      'будут сохранены, схема обновится скриптами 01/02.'#13#10#13#10 +
      'Перед установкой закройте MultiLogic Trade (окна API/Angular),'#13#10 +
      'если они открыты.'
  else
    TextLabel.Caption :=
      'New package: version {#MyAppVersion}, build {#MyAppBuild}.'#13#10#13#10 +
      'By default the setup will run over the existing installation: existing'#13#10 +
      'tables and data (prices, trades, logics, indicator parameters) will be'#13#10 +
      'kept and the schema will be updated by scripts 01/02.'#13#10#13#10 +
      'Please close MultiLogic Trade (API/Angular windows) before installing'#13#10 +
      'if it is running.';

  GWipeDataCheck := TNewCheckBox.Create(GUpgradePage);
  GWipeDataCheck.Parent := GUpgradePage.Surface;
  GWipeDataCheck.Left := 0;
  GWipeDataCheck.Top := TextLabel.Top + TextLabel.Height + 16;
  GWipeDataCheck.Width := GUpgradePage.SurfaceWidth;
  GWipeDataCheck.Checked := False;
  if ActiveLanguage = 'russian' then
    GWipeDataCheck.Caption := 'Удалить все таблицы и их содержимое и создать всё заново'
  else
    GWipeDataCheck.Caption := 'Delete all tables and their contents and recreate everything';
end;

procedure CurPageChanged(CurPageID: Integer);
begin
  if CurPageID = GUpgradePage.ID then
  begin
    WizardForm.BackButton.Visible := False;
    if ActiveLanguage = 'russian' then
      WizardForm.NextButton.Caption := 'Продолжить'
    else
      WizardForm.NextButton.Caption := 'Continue';
  end
  else
  begin
    WizardForm.BackButton.Visible := True;
    WizardForm.NextButton.Caption := SetupMessage(msgButtonNext);
  end;
end;

function ShouldSkipPage(PageID: Integer): Boolean;
begin
  Result := False;
  if PageID = GUpgradePage.ID then
    Result := not GInstalled;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
var
  ResultCode: Integer;
begin
  Result := True;
  if CurPageID = GUpgradePage.ID then
  begin
    if GWipeDataCheck.Checked then
    begin
      GDbMode := 'wipe';
      if (GUninstallString <> '') and
         (not Exec(StripQuotes(GUninstallString), '/VERYSILENT /SUPPRESSMSGBOXES /NORESTART', '', SW_SHOW, ewWaitUntilTerminated, ResultCode)) then
      begin
        if ActiveLanguage = 'russian' then
          MsgBox('Не удалось запустить деинсталлятор старой версии.', mbError, MB_OK)
        else
          MsgBox('Failed to run the old version uninstaller.', mbError, MB_OK);
        Result := False;
      end;
    end
    else
      GDbMode := 'upgrade';
  end;
end;

procedure PreparePostInstall();
var
  Max: Integer;
  ModePath: String;
  SslPath: String;
  SslFlag: String;
begin
  WizardForm.StatusLabel.Caption := 'Настройка приложения... См. INSTALL_PROTOCOL.txt';
  Max := WizardForm.ProgressGauge.Max;
  if Max > 0 then
    WizardForm.ProgressGauge.Position := (Max * 85) div 100;

  ModePath := ExpandConstant('{app}\installer\windows\db-mode.txt');
  ForceDirectories(ExtractFilePath(ModePath));
  SaveStringToFile(ModePath, GetDbMode('') + #13#10, False);

  SslPath := ExpandConstant('{app}\installer\windows\update-ssl-certs.txt');
  if WizardIsTaskSelected('updatesslcerts') then
    SslFlag := '1'
  else
    SslFlag := '0';
  SaveStringToFile(SslPath, SslFlag + #13#10, False);
end;

procedure FinishPostInstall();
begin
  WizardForm.ProgressGauge.Position := WizardForm.ProgressGauge.Max;
end;

function InstallProtocolExists(): Boolean;
begin
  Result := FileExists(ExpandConstant('{app}\INSTALL_PROTOCOL.txt'));
end;

function InitializeSetup(): Boolean;
begin
  Result := True;
  GDbMode := '';
  GInstalled := False;
  GUninstallString := '';

  if RegQueryStringValue(HKLM, 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppId}_is1', 'UninstallString', GUninstallString)
    or RegQueryStringValue(HKCU, 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppId}_is1', 'UninstallString', GUninstallString) then
    GInstalled := True;
end;
